<?php
if(!defined('ClassCms')) {exit();}
class layui {
    function stop() {
        Return E('系统组件,无法停止');
    }
    function uninstall() {
        Return E('系统组件,无法卸载');
    }
    function css($check=1) {
        if($check && G('css')){return '';}
        G('css',1);
        Return '<link rel="stylesheet" href="'.template_url().'css/layui.css" media="all">';
    }
    function js($check=1) {
        if($check && G('js')){return '';}
        G('js',1);
        Return '<script src="'.template_url().'layui.js"></script>';
    }
    function js_all($check=1) {
        if($check && G('js_all')){return '';}
        G('js_all',1);
        Return '<script src="'.template_url().'layui.all.js"></script>';
    }
    function icon_list() {
        Return array(
            'layui-icon-heart-fill'=>array('实心','&#xe68f;'),
            'layui-icon-heart'=>array('空心','&#xe68c;'),
            'layui-icon-light'=>array('亮度/晴','&#xe748;'),
            'layui-icon-time'=>array('时间/历史','&#xe68d;'),
            'layui-icon-bluetooth'=>array('蓝牙','&#xe689;'),
            'layui-icon-at'=>array('@艾特','&#xe687;'),
            'layui-icon-mute'=>array('静音','&#xe685;'),
            'layui-icon-mike'=>array('录音/麦克风','&#xe6dc;'),
            'layui-icon-key'=>array('密钥/钥匙','&#xe683;'),
            'layui-icon-gift'=>array('礼物/活动','&#xe627;'),
            'layui-icon-email'=>array('邮箱','&#xe618;'),
            'layui-icon-rss'=>array('RSS','&#xe808;'),
            'layui-icon-wifi'=>array('WiFi','&#xe7e0;'),
            'layui-icon-logout'=>array('退出/注销','&#xe682;'),
            'layui-icon-android'=>array('Android 安卓','&#xe684;'),
            'layui-icon-ios'=>array('Apple IOS 苹果','&#xe680;'),
            'layui-icon-windows'=>array('Windows','&#xe67f;'),
            'layui-icon-transfer'=>array('穿梭框','&#xe691;'),
            'layui-icon-service'=>array('客服','&#xe626;'),
            'layui-icon-subtraction'=>array('减','&#xe67e;'),
            'layui-icon-addition'=>array('加','&#xe624;'),
            'layui-icon-slider'=>array('滑块','&#xe714;'),
            'layui-icon-print'=>array('打印','&#xe66d;'),
            'layui-icon-export'=>array('导出','&#xe67d;'),
            'layui-icon-cols'=>array('列','&#xe610;'),
            'layui-icon-screen-restore'=>array('退出全屏','&#xe758;'),
            'layui-icon-screen-full'=>array('全屏','&#xe622;'),
            'layui-icon-rate-half'=>array('半星','&#xe6c9;'),
            'layui-icon-rate'=>array('星星-空心','&#xe67b;'),
            'layui-icon-rate-solid'=>array('星星-实心','&#xe67a;'),
            'layui-icon-cellphone'=>array('手机','&#xe678;'),
            'layui-icon-vercode'=>array('验证码','&#xe679;'),
            'layui-icon-login-wechat'=>array('微信','&#xe677;'),
            'layui-icon-login-qq'=>array('QQ','&#xe676;'),
            'layui-icon-login-weibo'=>array('微博','&#xe675;'),
            'layui-icon-password'=>array('密码','&#xe673;'),
            'layui-icon-username'=>array('用户名','&#xe66f;'),
            'layui-icon-refresh-3'=>array('刷新-粗','&#xe9aa;'),
            'layui-icon-auz'=>array('授权','&#xe672;'),
            'layui-icon-spread-left'=>array('左向右伸缩菜单','&#xe66b;'),
            'layui-icon-shrink-right'=>array('右向左伸缩菜单','&#xe668;'),
            'layui-icon-snowflake'=>array('雪花','&#xe6b1;'),
            'layui-icon-tips'=>array('提示说明','&#xe702;'),
            'layui-icon-note'=>array('便签','&#xe66e;'),
            'layui-icon-home'=>array('主页','&#xe68e;'),
            'layui-icon-senior'=>array('高级','&#xe674;'),
            'layui-icon-refresh'=>array('刷新','&#xe669;'),
            'layui-icon-refresh-1'=>array('刷新','&#xe666;'),
            'layui-icon-flag'=>array('旗帜','&#xe66c;'),
            'layui-icon-theme'=>array('主题','&#xe66a;'),
            'layui-icon-notice'=>array('消息-通知','&#xe667;'),
            'layui-icon-website'=>array('网站','&#xe7ae;'),
            'layui-icon-console'=>array('控制台','&#xe665;'),
            'layui-icon-face-surprised'=>array('表情-惊讶','&#xe664;'),
            'layui-icon-set'=>array('设置-空心','&#xe716;'),
            'layui-icon-template-1'=>array('模板','&#xe656;'),
            'layui-icon-app'=>array('应用','&#xe653;'),
            'layui-icon-template'=>array('模板','&#xe663;'),
            'layui-icon-praise'=>array('赞','&#xe6c6;'),
            'layui-icon-tread'=>array('踩','&#xe6c5;'),
            'layui-icon-male'=>array('男','&#xe662;'),
            'layui-icon-female'=>array('女','&#xe661;'),
            'layui-icon-camera'=>array('相机-空心','&#xe660;'),
            'layui-icon-camera-fill'=>array('相机-实心','&#xe65d;'),
            'layui-icon-more'=>array('菜单-水平','&#xe65f;'),
            'layui-icon-more-vertical'=>array('菜单-垂直','&#xe671;'),
            'layui-icon-rmb'=>array('金额-人民币','&#xe65e;'),
            'layui-icon-dollar'=>array('金额-美元','&#xe659;'),
            'layui-icon-diamond'=>array('钻石-等级','&#xe735;'),
            'layui-icon-fire'=>array('火','&#xe756;'),
            'layui-icon-return'=>array('返回','&#xe65c;'),
            'layui-icon-location'=>array('位置-地图','&#xe715;'),
            'layui-icon-read'=>array('办公-阅读','&#xe705;'),
            'layui-icon-survey'=>array('调查','&#xe6b2;'),
            'layui-icon-face-smile'=>array('表情-微笑','&#xe6af;'),
            'layui-icon-face-cry'=>array('表情-哭泣','&#xe69c;'),
            'layui-icon-cart-simple'=>array('购物车','&#xe698;'),
            'layui-icon-cart'=>array('购物车','&#xe657;'),
            'layui-icon-next'=>array('下一页','&#xe65b;'),
            'layui-icon-prev'=>array('上一页','&#xe65a;'),
            'layui-icon-upload-drag'=>array('上传-空心-拖拽','&#xe681;'),
            'layui-icon-upload'=>array('上传-实心','&#xe67c;'),
            'layui-icon-download-circle'=>array('下载-圆圈','&#xe601;'),
            'layui-icon-component'=>array('组件','&#xe857;'),
            'layui-icon-file-b'=>array('文件-粗','&#xe655;'),
            'layui-icon-user'=>array('用户','&#xe770;'),
            'layui-icon-find-fill'=>array('发现-实心','&#xe670;'),
            'layui-icon-loading'=>array('loading','&#xe63d;'),
            'layui-icon-loading-1'=>array('loading','&#xe63e;'),
            'layui-icon-add-1'=>array('添加','&#xe654;'),
            'layui-icon-play'=>array('播放','&#xe652;'),
            'layui-icon-pause'=>array('暂停','&#xe651;'),
            'layui-icon-headset'=>array('音频-耳机','&#xe6fc;'),
            'layui-icon-video'=>array('视频','&#xe6ed;'),
            'layui-icon-voice'=>array('语音-声音','&#xe688;'),
            'layui-icon-speaker'=>array('消息-通知-喇叭','&#xe645;'),
            'layui-icon-fonts-del'=>array('删除线','&#xe64f;'),
            'layui-icon-fonts-code'=>array('代码','&#xe64e;'),
            'layui-icon-fonts-html'=>array('HTML','&#xe64b;'),
            'layui-icon-fonts-strong'=>array('字体加粗','&#xe62b;'),
            'layui-icon-unlink'=>array('删除链接','&#xe64d;'),
            'layui-icon-picture'=>array('图片','&#xe64a;'),
            'layui-icon-link'=>array('链接','&#xe64c;'),
            'layui-icon-face-smile-b'=>array('表情-笑-粗','&#xe650;'),
            'layui-icon-align-left'=>array('左对齐','&#xe649;'),
            'layui-icon-align-right'=>array('右对齐','&#xe648;'),
            'layui-icon-align-center'=>array('居中对齐','&#xe647;'),
            'layui-icon-fonts-u'=>array('字体-下划线','&#xe646;'),
            'layui-icon-fonts-i'=>array('字体-斜体','&#xe644;'),
            'layui-icon-tabs'=>array('Tabs 选项卡','&#xe62a;'),
            'layui-icon-radio'=>array('单选框-选中','&#xe643;'),
            'layui-icon-circle'=>array('单选框-候选','&#xe63f;'),
            'layui-icon-edit'=>array('编辑','&#xe642;'),
            'layui-icon-share'=>array('分享','&#xe641;'),
            'layui-icon-delete'=>array('删除','&#xe640;'),
            'layui-icon-form'=>array('表单','&#xe63c;'),
            'layui-icon-cellphone-fine'=>array('手机-细体','&#xe63b;'),
            'layui-icon-dialogue'=>array('聊天 对话 沟通','&#xe63a;'),
            'layui-icon-fonts-clear'=>array('文字格式化','&#xe639;'),
            'layui-icon-layer'=>array('窗口','&#xe638;'),
            'layui-icon-date'=>array('日期','&#xe637;'),
            'layui-icon-water'=>array('水 下雨','&#xe636;'),
            'layui-icon-code-circle'=>array('代码-圆圈','&#xe635;'),
            'layui-icon-carousel'=>array('轮播组图','&#xe634;'),
            'layui-icon-prev-circle'=>array('翻页','&#xe633;'),
            'layui-icon-layouts'=>array('布局','&#xe632;'),
            'layui-icon-util'=>array('工具','&#xe631;'),
            'layui-icon-templeate-1'=>array('选择模板','&#xe630;'),
            'layui-icon-upload-circle'=>array('上传-圆圈','&#xe62f;'),
            'layui-icon-tree'=>array('树','&#xe62e;'),
            'layui-icon-table'=>array('表格','&#xe62d;'),
            'layui-icon-chart'=>array('图表','&#xe62c;'),
            'layui-icon-chart-screen'=>array('图标 报表 屏幕','&#xe629;'),
            'layui-icon-engine'=>array('引擎','&#xe628;'),
            'layui-icon-triangle-d'=>array('下三角','&#xe625;'),
            'layui-icon-triangle-r'=>array('右三角','&#xe623;'),
            'layui-icon-file'=>array('文件','&#xe621;'),
            'layui-icon-set-sm'=>array('设置-小型','&#xe620;'),
            'layui-icon-reduce-circle'=>array('减少-圆圈','&#xe616'),
            'layui-icon-add-circle'=>array('添加-圆圈','&#xe61f;'),
            'layui-icon-404'=>array('404','&#xe61c;'),
            'layui-icon-about'=>array('关于','&#xe60b;'),
            'layui-icon-up'=>array('箭头 向上','&#xe619;'),
            'layui-icon-down'=>array('箭头 向下','&#xe61a;'),
            'layui-icon-left'=>array('箭头 向左','&#xe603;'),
            'layui-icon-right'=>array('箭头 向右','&#xe602;'),
            'layui-icon-circle-dot'=>array('圆点','&#xe617;'),
            'layui-icon-search'=>array('搜索','&#xe615;'),
            'layui-icon-set-fill'=>array('设置-实心','&#xe614;'),
            'layui-icon-group'=>array('群组','&#xe613;'),
            'layui-icon-friends'=>array('好友','&#xe612;'),
            'layui-icon-reply-fill'=>array('回复 评论 实心','&#xe611;'),
            'layui-icon-menu-fill'=>array('菜单 隐身 实心','&#xe60f;'),
            'layui-icon-log'=>array('记录','&#xe60e;'),
            'layui-icon-picture-fine'=>array('图片-细体','&#xe60d;'),
            'layui-icon-face-smile-fine'=>array('表情-笑-细体','&#xe60c;'),
            'layui-icon-list'=>array('列表','&#xe60a;'),
            'layui-icon-release'=>array('发布 纸飞机','&#xe609;'),
            'layui-icon-ok'=>array('对 OK','&#xe605;'),
            'layui-icon-help'=>array('帮助','&#xe607;'),
            'layui-icon-chat'=>array('客服','&#xe606;'),
            'layui-icon-top'=>array('top 置顶','&#xe604;'),
            'layui-icon-star'=>array('收藏-空心','&#xe600;'),
            'layui-icon-star-fill'=>array('收藏-实心','&#xe658;'),
            'layui-icon-close-fill'=>array('关闭-实心','&#x1007;'),
            'layui-icon-close'=>array('关闭-空心','&#x1006;'),
            'layui-icon-ok-circle'=>array('正确','&#x1005;'),
            'layui-icon-add-circle-fine'=>array('添加-圆圈-细体','&#xe608;'),
        );
    }
}